development:
  adapter: async
  # url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: async
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: api_production
